chore: add library_type to .repo-metadata.json
googleapis/ruby-cloud-env pull request #18
Opened 2021-05-13 16:12 UTC by trambui09

Add an additional field called library_type to the .repo-metadata.json file. This is part of internal issue #184315365.

2021-05-17 18:07 UTC, dazuma requested changes

2021-05-17 18:07 UTC, dazuma commented on .repo-metadata.json
> +    "library_type": "GAPIC_MANUAL"
This one is CORE.

2021-05-18 00:15 UTC, trambui09 commented
updated the library_type to CORE!

2021-05-18 22:51 UTC, dazuma approved these changes

2021-05-18 22:51 UTC, merged